compile:
	gcc -I/opt/local/include -L/opt/local/lib -lgmp fib1.c -o fib1
	gcc -I/opt/local/include -L/opt/local/lib -lgmp fib2.c -o fib2
	gcc -I/opt/local/include -L/opt/local/lib -lgmp fib3.c -o fib3

clean:
	rm fib1 fib2 fib3
